version: "4.0"
services:
  mssql:
    container_name: jaeger_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '1439:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Standard
      - SA_PASSWORD=P@ssword
      - MSSQL_AGENT_ENABLED=true
    volumes:
     - ./sqlserver:/var/opt/mssql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true

